version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.1
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec jekyll build

  test:
      docker:
        - image: circleci/ruby:2.6.1
      steps:
        - checkout
        - run: bundle exec htmlproofer ./_site --allow-hash-href --check-html --disable-external
